version: 16
jobs:
- name: update
  steps:
  - !PushRepository
    name: push to remote
    remoteUrl: https://github.com/mehalter/nice60-zmk-config.git
    userName: mehalter
    passwordSecret: github_pat
    withLfs: true
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
